### ISSUE TITLE
Add Toleration and NodeSelector options to Donkey container

### ISSUE THREAD

**Issue by ajadams-T4** [fivetran/hybrid_deployment#10]
I recently tried out the Fivetran Helm chart (version 0.1.0) and successfully deployed Fivetran in AKS. Using the tolerations and nodeSelector settings available in the Helm chart values, I was able to deploy the hdagent (controller pod) to the correct node pool.

However, I noticed that the test runner pod and the donkey pods do not inherit the tolerations and nodeSelector configurations specified in the Helm values. This inconsistency prevents these pods from being scheduled on the desired node pool, which is crucial for our workload management and cost optimization

```
node_selector:
  kubernetes.azure.com/scalesetpriority: "spot"
tolerations:
  - key: "kubernetes.azure.com/scalesetpriority"
    operator: "Equal"
    value: "spot"
    effect: "NoSchedule"
```
